# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  # Database VM
  config.vm.define "db01" do |db01|
    db01.vm.box = "eurolinux-vagrant/centos-stream-9"
    db01.vm.hostname = "database"
    db01.vm.network "private_network", ip: "192.168.33.10"
    db01.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
    db01.vm.provision "shell", path: "mysql.sh"
  end

  # Memcache Vm
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "eurolinux-vagrant/centos-stream-9"
    mc01.vm.hostname = "memcache"
    mc01.vm.network "private_network", ip: "192.168.33.11"
    mc01.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
    mc01.vm.provision "shell", path: "memcache.sh"
  end

  # Rabbit MQ VM
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "eurolinux-vagrant/centos-stream-9"
    rmq01.vm.hostname = "rabbitmq"
    rmq01.vm.network "private_network", ip: "192.168.33.12"
    rmq01.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
    rmq01.vm.provision "shell", path: "rabbitmq.sh"
  end

  # Tomcat VM
  config.vm.define "app01" do |app01|
    app01.vm.box = "eurolinux-vagrant/centos-stream9"
    app01.vm.hostname = "tomcat"
    app01.vm.network "private_network", ip: "192.168.33.13"
    app01.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
    app01.vm.provision "shell", path: "tomcat.sh"
  end

  # Nginx
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"
    web01.vm.hostname = "nginx"
    web01.vm.network "private_network", ip: "192.168.33.14"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
    web01.vm.provision "shell", path: "nginx.sh"
  end
  
end